http = false
https = true
ipv4 = true
ipv6 = true
countries = [
  "Australia",
  "Canada",
  "China",
  "Denmark",
  "Finland",
  "France",
  "Germany",
  "India",
  "Indonesia",
  "Japan",
  "Taiwan",
  "United States"]
